### ISSUE TITLE
CommonOres repo doesn't have Chisel Assets

### ISSUE THREAD

**Issue by nmarshall23** [reteo/JMOD-Collection#1]
Just a heads up, the repo doesn't have the Chisel Assets.

**Comment by reteo** [comment]
What do you mean?

**Comment by nmarshall23** [comment]
The CommonOres-1.0.jmod, file has Chisel pngs that are not in the repo.

**Comment by reteo** [comment]
Thanks for the heads up; I'd made some changes, and forgot to add the new files to the repo.  Particularly Moh's Mining and Vanilla Ingot Works.
